# Welcome to Jekyll!
# Description of the site
title: Logs
author:
  name: TJK
  email: rawinbox@protonmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This is a collection of logs written as an open reflection.   

# Shows excerpts of the blog posts
show_excerpts: true

# URL structure
baseurl: ""
url: "https://timo-juhani.github.io/"

# Minima theme settings
minima:
  skin: dark
  date_format: "%Y-%m-%d"
  social_links:
    github: timo-juhani
    linkedin: tjkarjalainen
    twitter: tj_karjalainen
    
# Build settings
remote_theme: jekyll/minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme
