# Welcome to Jekyll!
# Description of the site
title: Logs
# author: TJK
description: >- # this means to ignore newlines until "baseurl:"
  This is a collection of logs written as an open reflection.   

# Shows excerpts of the blog posts
show_excerpts: true

# URL structure
baseurl: ""
url: "https://timo-juhani.github.io/"

# Social media settings
# twitter_username: tj_karjalainen
# github_username: timo-juhani
# linkedin_username: tjkarjalainen

minima:
  skin: dark
  date_format: "%Y-%m-%d"

theme: minima

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
